//
//  CategoryItem.swift
//  Who is the spy
//
//  Created by Motlaq Alnassafi on 23/02/2025.
//

import SwiftUICore

struct CategoryItem: Identifiable, Hashable {
    var id = UUID()
    var name: String
    var emoji: String

    static var generalLocations = [
        CategoryItem(name: "Synagogue".localized, emoji: "synagouge"),
        CategoryItem(name: "Mosque".localized, emoji: "mosque"),
        CategoryItem(name: "Church".localized, emoji: "church"),
        CategoryItem(name: "TheSun".localized, emoji: "Sun"),
        CategoryItem(name: "TheMoon".localized, emoji: "Moon"),
        CategoryItem(name: "Camping".localized, emoji: "camping"),
        CategoryItem(name: "HellFire".localized, emoji: "hell"),
        CategoryItem(name: "Haven".localized, emoji: "Haven"),
        CategoryItem(name: "BarbarShop".localized, emoji: "barber"),
        CategoryItem(name: "SuperMarket".localized, emoji: "SuperMarket"),
        CategoryItem(name: "Chalat".localized, emoji: "Chalat"),
        CategoryItem(name: "Zoo".localized, emoji: "Zoo"),
        CategoryItem(name: "FishMarket".localized, emoji: "FishMarket"),
        CategoryItem(name: "IceSkatingRing".localized, emoji: "Skating"),
        CategoryItem(name: "Cinema".localized, emoji: "Cinema"),
        CategoryItem(name: "AmusementPark".localized, emoji: "amusementPark"),
        CategoryItem(name: "Spa".localized, emoji: "Spa"),
        CategoryItem(name: "Gym".localized, emoji: "Gym"),
        CategoryItem(name: "Hotel".localized, emoji: "Hotel"),
        CategoryItem(name: "Bank".localized, emoji: "Bank"),
        CategoryItem(name: "Court".localized, emoji: "Court"),
        CategoryItem(name: "FireStation".localized, emoji: "FireStation"),
        CategoryItem(name: "PoliceStation".localized, emoji: "PoliceStation"),
        CategoryItem(name: "Factory".localized, emoji: "Factory"),
        CategoryItem(name: "University".localized, emoji: "University"),
        CategoryItem(name: "School".localized, emoji: "School"),
        CategoryItem(name: "Harbor".localized, emoji: "Harbor"),
        CategoryItem(name: "BusStation".localized, emoji: "BusStation"),
        CategoryItem(name: "TrainStation".localized, emoji: "TrainStation"),
        CategoryItem(name: "Airport".localized, emoji: "AirPort"),
        CategoryItem(name: "Pharmacy".localized, emoji: "Pharmacy"),
        CategoryItem(name: "Hospital".localized, emoji: "Hospital"),
        CategoryItem(name: "Bakery".localized, emoji: "Bakery"),
        CategoryItem(name: "Cafe".localized, emoji: "Cafe"),
        CategoryItem(name: "Restaurant".localized, emoji: "Restaurant"),
        CategoryItem(name: "Theater".localized, emoji: "Theater"),
        CategoryItem(name: "Museum".localized, emoji: "Museum"),
        CategoryItem(name: "Cave".localized, emoji: "Cave"),
        CategoryItem(name: "Library".localized, emoji: "Library"),
        CategoryItem(name: "Mall".localized, emoji: "Mall"),
        CategoryItem(name: "Bridge".localized, emoji: "Bridge"),
        CategoryItem(name: "Park".localized, emoji: "Park"),
        CategoryItem(name: "Forest".localized, emoji: "Forest"),
        CategoryItem(name: "UndergroundTunnel".localized, emoji: "UndergroundTunnel"),
        CategoryItem(name: "ParkingLot".localized, emoji: "CarPark"),
        CategoryItem(name: "GasStation".localized, emoji: "GasStation"),
        CategoryItem(name: "CarWash".localized, emoji: "CarWash"),
        CategoryItem(name: "Elevator".localized, emoji: "Elevator"),
        CategoryItem(name: "Farm".localized, emoji: "Farm"),
        CategoryItem(name: "LaundryMat".localized, emoji: "LaundryMat"),
        CategoryItem(name: "CarDealerShip".localized, emoji: "CarDealerShip"),
        CategoryItem(name: "Funeral".localized, emoji: "Funeral"),
        CategoryItem(name: "PoliceStop".localized, emoji: "PoliceStop"),
        CategoryItem(name: "Jail".localized, emoji: "Jail"),
        CategoryItem(name: "AirPlane".localized, emoji: "AirPlane"),
        CategoryItem(name: "Submarine".localized, emoji: "Submarine"),
        CategoryItem(name: "GraveYard".localized, emoji: "GraveYard"),
        CategoryItem(name: "BeautySalon".localized, emoji: "BeautySalon"),
        CategoryItem(name: "HotAirBaloon".localized, emoji: "HotAirBaloon"),
    ].shuffled()

    static var KuwaitLocations = [
        CategoryItem(name: "KuwaitTowers".localized, emoji: "KuwaitTowers"),
        CategoryItem(name: "TheWalk".localized, emoji: "Mall"),
        CategoryItem(name: "JaberBridge".localized, emoji: "Bridge"),
        CategoryItem(name: "NationalAssembly".localized, emoji: "NationalAssembly"),
        CategoryItem(name: "JACC".localized, emoji: "Mall"),
        CategoryItem(name: "SouqAl-Mubarakiya".localized, emoji: "Mall"),
        CategoryItem(name: "GrandMosque".localized, emoji: "mosque"),
        CategoryItem(name: "AlShaheedPark".localized, emoji: "Park"),
        CategoryItem(name: "SouqSharq".localized, emoji: "Mall"),
        CategoryItem(name: "TheScientificCenter".localized, emoji: "TheScientificCenter"),
        CategoryItem(name: "KuwaitZoo".localized, emoji: "Zoo"),
        CategoryItem(name: "EntertainmentCity".localized, emoji: "amusementPark"),
        CategoryItem(name: "SeifPalace".localized, emoji: "Palace"),
        CategoryItem(name: "TheAvenues".localized, emoji: "Mall"),
        CategoryItem(name: "SabahAlAhmadNatureReserve".localized, emoji: "Forest"),
        CategoryItem(name: "FridayMarket".localized, emoji: "Mall"),
        CategoryItem(name: "LiberationTower".localized, emoji: "tower"),
        CategoryItem(name: "KuwaitEquestrianClub".localized, emoji: "KuwaitEquestrianClub"),
        CategoryItem(name: "KuwaitNationalLibrary".localized, emoji: "Library"),
        CategoryItem(name: "FailakaIsland".localized, emoji: "Island"),
        CategoryItem(name: "AlRayaMall".localized, emoji: "Mall"),
        CategoryItem(name: "KhiranResort".localized, emoji: "Chalat"),
        CategoryItem(name: "360Mall".localized, emoji: "Mall"),
        CategoryItem(name: "QadsiaSportsClub".localized, emoji: "QadsiaSportsClub"),
        CategoryItem(name: "AlKoutMall".localized, emoji: "Mall"),
        CategoryItem(name: "FishMarket".localized, emoji: "FishMarket"),
        CategoryItem(name: "MuroojComplex".localized, emoji: "Mall"),
        CategoryItem(name: "KuwaitOperaHouse".localized, emoji: "KuwaitOperaHouse"),
        CategoryItem(name: "KuwaitInternationalAirport".localized, emoji: "AirPort"),
        CategoryItem(name: "JaberInternationalStadium".localized, emoji: "JaberInternationalStadium"),
        CategoryItem(name: "ShuwaikhIndustrialArea".localized, emoji: "Factory"),
        CategoryItem(name: "KuwaitUniversity".localized, emoji: "University"),
    ].shuffled()

    static var animals = [
        CategoryItem(name: "Camel".localized, emoji: "Camel"),
        CategoryItem(name: "Lion".localized, emoji: "Lion"),
        CategoryItem(name: "Tiger".localized, emoji: "Tiger"),
        CategoryItem(name: "Elephant".localized, emoji: "Elephant"),
        CategoryItem(name: "Horse".localized, emoji: "Horse"),
        CategoryItem(name: "Dog".localized, emoji: "Dog"),
        CategoryItem(name: "Cat".localized, emoji: "Cat"),
        CategoryItem(name: "Wolf".localized, emoji: "Wolf"),
        CategoryItem(name: "Bear".localized, emoji: "Bear"),
        CategoryItem(name: "Rabbit".localized, emoji: "Rabbit"),
        CategoryItem(name: "Monkey".localized, emoji: "Monkey"),
        CategoryItem(name: "Cow".localized, emoji: "Cow"),
        CategoryItem(name: "Sheep".localized, emoji: "Sheep"),
        CategoryItem(name: "Goat".localized, emoji: "Goat"),
        CategoryItem(name: "Eagle".localized, emoji: "Eagle"),
        CategoryItem(name: "Falcon".localized, emoji: "Falcon"),
        CategoryItem(name: "Owl".localized, emoji: "Owl"),
        CategoryItem(name: "Parrot".localized, emoji: "Parrot"),
        CategoryItem(name: "Pigeon".localized, emoji: "Pigeon"),
        CategoryItem(name: "Snake".localized, emoji: "Snake"),
        CategoryItem(name: "Turtle".localized, emoji: "Turtle"),
        CategoryItem(name: "Frog".localized, emoji: "Frog"),
        CategoryItem(name: "Fish".localized, emoji: "Fish"),
        CategoryItem(name: "Shark".localized, emoji: "Shark"),
        CategoryItem(name: "Dolphin".localized, emoji: "Dolphin"),
        CategoryItem(name: "Whale".localized, emoji: "Whale"),
        CategoryItem(name: "Octopus".localized, emoji: "Octopus"),
        CategoryItem(name: "Bee".localized, emoji: "Bee"),
        CategoryItem(name: "Ant".localized, emoji: "Ant"),
        CategoryItem(name: "Butterfly".localized, emoji: "Butterfly"),
        CategoryItem(name: "Spider".localized, emoji: "Spider"),
        CategoryItem(name: "Cheetah".localized, emoji: "Cheetah"),
        CategoryItem(name: "Hippopotamus".localized, emoji: "Hippopotamus"),
        CategoryItem(name: "Rhinoceros".localized, emoji: "Rhinoceros"),
        CategoryItem(name: "Giraffe".localized, emoji: "Giraffe"),
        CategoryItem(name: "Zebra".localized, emoji: "Zebra"),
        CategoryItem(name: "Buffalo".localized, emoji: "Buffalo"),
        CategoryItem(name: "Deer".localized, emoji: "Deer"),
        CategoryItem(name: "Kangaroo".localized, emoji: "Kangaroo"),
        CategoryItem(name: "Koala".localized, emoji: "Koala"),
        CategoryItem(name: "Panda".localized, emoji: "Panda"),
        CategoryItem(name: "Hedgehog".localized, emoji: "Hedgehog"),
        CategoryItem(name: "Squirrel".localized, emoji: "Squirrel"),
        CategoryItem(name: "Bat".localized, emoji: "Bat"),
        CategoryItem(name: "Fox".localized, emoji: "Fox"),
        CategoryItem(name: "Crocodile".localized, emoji: "Crocodile"),
        CategoryItem(name: "Penguin".localized, emoji: "Penguin"),
        CategoryItem(name: "Peacock".localized, emoji: "Peacock"),
        CategoryItem(name: "Flamingo".localized, emoji: "Flamingo"),
        CategoryItem(name: "Goose".localized, emoji: "Goose"),
        CategoryItem(name: "Swan".localized, emoji: "Swan"),
        CategoryItem(name: "Woodpecker".localized, emoji: "Woodpecker"),
        CategoryItem(name: "Eel".localized, emoji: "Eel"),
        CategoryItem(name: "Jellyfish".localized, emoji: "Jellyfish"),
        CategoryItem(name: "Seahorse".localized, emoji: "Seahorse"),
        CategoryItem(name: "Starfish".localized, emoji: "Starfish"),
        CategoryItem(name: "Crab".localized, emoji: "Crab"),
        CategoryItem(name: "Scorpion".localized, emoji: "Scorpion"),
        CategoryItem(name: "Beetle".localized, emoji: "Beetle"),
        CategoryItem(name: "Grasshopper".localized, emoji: "Grasshopper"),
        CategoryItem(name: "Seal".localized, emoji: "Seal"),
        CategoryItem(name: "Hyena".localized, emoji: "Hyena"),
    ].shuffled()

    static var kuwaitAreas = [
        CategoryItem(name: "Jaber Al-Ahmed".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Abdulla Al-Salem".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Adailiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Bnaid Al-Qar".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Daiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Dasma".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Dasman".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Doha".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Doha Port".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Faiha".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Granada".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jibla".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Kaifan".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Khaldiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mansouriya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mirqab".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Nahdha".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "North West Sulaibikhat".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Nuzha".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Qadsiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Qortuba".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Rawda".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Shamiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sharq".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Shuwaikh".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Shuwaikh Industrial Area".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Shuwaikh Port".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sulaibikhat".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Qairawan".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Surra".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Yarmouk".localized, emoji: "KuwaitAreas"),

        CategoryItem(name: "Bayan".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jabriya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Rumaithiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Salam".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Salwa".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Bida'a".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Hawalli".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Hitteen".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mishrif".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mubarak Al-Abdullah".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Salmiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Shaab".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Shuhada".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Siddiq".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Zahra".localized, emoji: "KuwaitAreas"),

        CategoryItem(name: "Abu Al Hasaniya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Abu Ftaira".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Adan".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al Qurain".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Qusour".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Fnaitees".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Messila".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Masayel".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mubarak Al-Kabeer".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sabah Al-Salem".localized, emoji: "KuwaitAreas"),

        CategoryItem(name: "Abu Halifa".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mina Abdulla".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Ahmadi".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Ali Sabah Al-Salem".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Egaila".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Bnaider".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Dhaher".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Fahaheel".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Fahad Al-Ahmad".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Hadiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jaber Al-Ali".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Julaia'a".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Khairan".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mahboula".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Mangaf".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Magwa".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Wafra Residential".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Nuwaiseeb".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Riqqa".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sabah Al Ahmad".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sabah Al Ahmad Sea City".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sabahiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Wafra".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Zoor".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Fintas".localized, emoji: "KuwaitAreas"),

        CategoryItem(name: "Abdullah Al-Mubarak".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Andalus".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Ardiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Ardiya Herafiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Ishbiliya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Dajeej".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Farwaniya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Firdous".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jleeb Al-Shuyoukh".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Khaitan".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Omariya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Rabiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Rai".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Riggai".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Rehab".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sabah Al-Nasser".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "West Abdullah Al-Mubarak".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "South Abdullah Al-Mubarak".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sulaibiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sulaibiya Industrial".localized, emoji: "KuwaitAreas"),

        CategoryItem(name: "Abdali".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Mutlaa".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Kazma".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Kabd".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Al-Nahda".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Amghara Industrial".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jahra".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jahra Industrial Herafiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Naeem".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Nasseem".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Oyoun".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Qasr".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Jaber Al-Ahmad".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Saad Al Abdullah".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Salmi".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Subiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sulaibiya".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Sulaibiya Agricultural Area".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Taima".localized, emoji: "KuwaitAreas"),
        CategoryItem(name: "Waha".localized, emoji: "KuwaitAreas"),
    ].shuffled()
}
