//
//  Location.swift
//  Who is the spy
//
//  Created by Motlaq Alnassafi on 23/02/2025.
//

import SwiftUICore

struct Location: Identifiable, Hashable {
    var id = UUID()
    var name: String
    var emoji: String

    static var generalLocations = [
        Location(name: "Synagogue".localized, emoji: "synagouge"),
        Location(name: "Mosque".localized, emoji: "mosque"),
        Location(name: "Church".localized, emoji: "church"),
        Location(name: "TheSun".localized, emoji: "Sun"),
        Location(name: "TheMoon".localized, emoji: "Moon"),
        Location(name: "Camping".localized, emoji: "camping"),
        Location(name: "HellFire".localized, emoji: "hell"),
        Location(name: "Haven".localized, emoji: "Haven"),
        Location(name: "BarbarShop".localized, emoji: "barber"),
        Location(name: "SuperMarket".localized, emoji: "SuperMarket"),
        Location(name: "Chalat".localized, emoji: "Chalat"),
        Location(name: "Zoo".localized, emoji: "Zoo"),
        Location(name: "FishMarket".localized, emoji: "FishMarket"),
        Location(name: "IceSkatingRing".localized, emoji: "Skating"),
        Location(name: "Cinema".localized, emoji: "Cinema"),
        Location(name: "AmusementPark".localized, emoji: "amusementPark"),
        Location(name: "Spa".localized, emoji: "Spa"),
        Location(name: "Gym".localized, emoji: "Gym"),
        Location(name: "Hotel".localized, emoji: "Hotel"),
        Location(name: "Bank".localized, emoji: "Bank"),
        Location(name: "Court".localized, emoji: "Court"),
        Location(name: "FireStation".localized, emoji: "FireStation"),
        Location(name: "PoliceStation".localized, emoji: "PoliceStation"),
        Location(name: "Factory".localized, emoji: "Factory"),
        Location(name: "University".localized, emoji: "University"),
        Location(name: "School".localized, emoji: "School"),
        Location(name: "Harbor".localized, emoji: "Harbor"),
        Location(name: "BusStation".localized, emoji: "BusStation"),
        Location(name: "TrainStation".localized, emoji: "TrainStation"),
        Location(name: "Airport".localized, emoji: "AirPort"),
        Location(name: "Pharmacy".localized, emoji: "Pharmacy"),
        Location(name: "Hospital".localized, emoji: "Hospital"),
        Location(name: "Bakery".localized, emoji: "Bakery"),
        Location(name: "Cafe".localized, emoji: "Cafe"),
        Location(name: "Restaurant".localized, emoji: "Restaurant"),
        Location(name: "Theater".localized, emoji: "Theater"),
        Location(name: "Museum".localized, emoji: "Museum"),
        Location(name: "Cave".localized, emoji: "Cave"),
        Location(name: "Library".localized, emoji: "Library"),
        Location(name: "Mall".localized, emoji: "Mall"),
        Location(name: "Bridge".localized, emoji: "Bridge"),
        Location(name: "Park".localized, emoji: "Park"),
        Location(name: "Forest".localized, emoji: "Forest"),
        Location(name: "UndergroundTunnel".localized, emoji: "UndergroundTunnel"),
        Location(name: "ParkingLot".localized, emoji: "CarPark"),
        Location(name: "GasStation".localized, emoji: "GasStation"),
        Location(name: "CarWash".localized, emoji: "CarWash"),
        Location(name: "Elevator".localized, emoji: "Elevator"),
        Location(name: "Farm".localized, emoji: "Farm"),
        Location(name: "LaundryMat".localized, emoji: "LaundryMat"),
        Location(name: "CarDealerShip".localized, emoji: "CarDealerShip"),
        Location(name: "Funeral".localized, emoji: "Funeral"),
        Location(name: "PoliceStop".localized, emoji: "PoliceStop"),
        Location(name: "Jail".localized, emoji: "Jail"),
        Location(name: "AirPlane".localized, emoji: "AirPlane"),
        Location(name: "Submarine".localized, emoji: "Submarine"),
        Location(name: "GraveYard".localized, emoji: "GraveYard"),
        Location(name: "BeautySalon".localized, emoji: "BeautySalon"),
    ].shuffled()

    static var KuwaitLocations = [
        Location(name: "KuwaitTowers".localized, emoji: "KuwaitTowers"),
        Location(name: "TheWalk".localized, emoji: "Mall"),
        Location(name: "JaberBridge".localized, emoji: "Bridge"),
        Location(name: "NationalAssembly".localized, emoji: "NationalAssembly"),
        Location(name: "JACC".localized, emoji: "Mall"),
        Location(name: "SouqAl-Mubarakiya".localized, emoji: "Mall"),
        Location(name: "GrandMosque".localized, emoji: "mosque"),
        Location(name: "AlShaheedPark".localized, emoji: "Park"),
        Location(name: "SouqSharq".localized, emoji: "Mall"),
        Location(name: "TheScientificCenter".localized, emoji: "TheScientificCenter"),
        Location(name: "KuwaitZoo".localized, emoji: "Zoo"),
        Location(name: "EntertainmentCity".localized, emoji: "amusementPark"),
        Location(name: "SeifPalace".localized, emoji: "Palace"),
        Location(name: "TheAvenues".localized, emoji: "Mall"),
        Location(name: "SabahAlAhmadNatureReserve".localized, emoji: "Forest"),
        Location(name: "FridayMarket".localized, emoji: "Mall"),
        Location(name: "LiberationTower".localized, emoji: "tower"),
        Location(name: "KuwaitEquestrianClub".localized, emoji: "KuwaitEquestrianClub"),
        Location(name: "KuwaitNationalLibrary".localized, emoji: "Library"),
        Location(name: "FailakaIsland".localized, emoji: "Island"),
        Location(name: "AlRayaMall".localized, emoji: "Mall"),
        Location(name: "KhiranResort".localized, emoji: "Chalat"),
        Location(name: "360Mall".localized, emoji: "Mall"),
        Location(name: "QadsiaSportsClub".localized, emoji: "QadsiaSportsClub"),
        Location(name: "AlKoutMall".localized, emoji: "Mall"),
        Location(name: "FishMarket".localized, emoji: "FishMarket"),
        Location(name: "MuroojComplex".localized, emoji: "Mall"),
        Location(name: "KuwaitOperaHouse".localized, emoji: "KuwaitOperaHouse"),
        Location(name: "KuwaitInternationalAirport".localized, emoji: "AirPort"),
        Location(name: "JaberInternationalStadium".localized, emoji: "JaberInternationalStadium"),
        Location(name: "ShuwaikhIndustrialArea".localized, emoji: "Factory"),
        Location(name: "KuwaitUniversity".localized, emoji: "University"),
    ].shuffled()
}
