//
//  Location.swift
//  Who is the spy
//
//  Created by Motlaq Alnassafi on 23/02/2025.
//

import SwiftUICore

struct Location: Identifiable, Hashable {
    var id = UUID()
    var name: String
    var emoji: String
    var color: Color

    static var generalLocations = [
        Location(name: "Synagogue".localized, emoji: "🕍", color: .gray),
        Location(name: "Mosque".localized, emoji: "🕌", color: .gray),
        Location(name: "Church".localized, emoji: "⛪️", color: .gray),
        Location(name: "TheSun".localized, emoji: "☀️", color: .gray),
        Location(name: "TheMoon".localized, emoji: "🌑", color: .gray),
        Location(name: "Camping".localized, emoji: "🏜️", color: .gray),
        Location(name: "HellFire".localized, emoji: "👹", color: .gray),
        Location(name: "Haven".localized, emoji: "😇", color: .gray),
        Location(name: "LuandryMat".localized, emoji: "👔", color: .gray),
        Location(name: "Farm".localized, emoji: "👨🏻‍🌾", color: .gray),
        Location(name: "CarDealerShip".localized, emoji: "🚘", color: .gray),
        Location(name: "BarbarShop".localized, emoji: "💈", color: .gray),
        Location(name: "SuperMarket".localized, emoji: "🏪", color: .gray),
        Location(name: "Chalat".localized, emoji: "🌊", color: .gray),
        Location(name: "Zoo".localized, emoji: "🦁", color: .gray),
        Location(name: "FishMarket".localized, emoji: "🐟", color: .gray),
        Location(name: "IceSkatingRink".localized, emoji: "⛸️", color: .gray),
        Location(name: "Cinema".localized, emoji: "🎥", color: .gray),
        Location(name: "AmusementPark".localized, emoji: "🎢", color: .gray),
        Location(name: "Spa".localized, emoji: "💆", color: .gray),
        Location(name: "Gym".localized, emoji: "🏋️", color: .gray),
        Location(name: "Hotel".localized, emoji: "🏨", color: .gray),
        Location(name: "Bank".localized, emoji: "🏦", color: .gray),
        Location(name: "Court".localized, emoji: "⚖️", color: .gray),
        Location(name: "FireStation".localized, emoji: "🚒", color: .gray),
        Location(name: "PoliceStation".localized, emoji: "🚓", color: .gray),
        Location(name: "Factory".localized, emoji: "🏭", color: .gray),
        Location(name: "University".localized, emoji: "🎓", color: .gray),
        Location(name: "School".localized, emoji: "🏫", color: .gray),
        Location(name: "Harbor".localized, emoji: "⚓", color: .gray),
        Location(name: "BusStation".localized, emoji: "🚏", color: .gray),
        Location(name: "TrainStation".localized, emoji: "🚉", color: .gray),
        Location(name: "Airport".localized, emoji: "🛫", color: .gray),
        Location(name: "Pharmacy".localized, emoji: "💊", color: .gray),
        Location(name: "Hospital".localized, emoji: "🏥", color: .gray),
        Location(name: "Bakery".localized, emoji: "🥐", color: .gray),
        Location(name: "Cafe".localized, emoji: "☕", color: .gray),
        Location(name: "Restaurant".localized, emoji: "🍽️", color: .gray),
        Location(name: "Theater".localized, emoji: "🎭", color: .gray),
        Location(name: "Museum".localized, emoji: "🏛️", color: .gray),
        Location(name: "Library".localized, emoji: "📚", color: .gray),
        Location(name: "Mall".localized, emoji: "🏬", color: .gray),
        Location(name: "Bridge".localized, emoji: "🌉", color: .gray),
        Location(name: "Park".localized, emoji: "🏞️", color: .gray),
        Location(name: "Cave".localized, emoji: "🕳️", color: .gray),
        Location(name: "Forest".localized, emoji: "🌲", color: .gray),
        Location(name: "Skyscraper".localized, emoji: "🏙️", color: .gray),
        Location(name: "UndergroundTunnel".localized, emoji: "🚇", color: .gray),
        Location(name: "ParkingLot".localized, emoji: "🅿️", color: .gray),
        Location(name: "GasStation".localized, emoji: "⛽", color: .gray),
        Location(name: "CarWash".localized, emoji: "🚗", color: .gray),
        Location(name: "Elevator".localized, emoji: "🛗", color: .gray),
    ].shuffled()

    static var locations = [
        Location(name: "Synagogue".localized, emoji: "🕍", color: .gray),
        Location(name: "KuwaitTowers".localized, emoji: "🗼", color: .gray),
        Location(name: "Mosque".localized, emoji: "🕌", color: .gray),
        Location(name: "TheWalk".localized, emoji: "💰", color: .gray),
        Location(name: "JaberBridge".localized, emoji: "🌉", color: .gray),
        Location(name: "Chalat".localized, emoji: "🌊", color: .gray),
        Location(name: "NationalAssembly".localized, emoji: "🏬", color: .gray),
        Location(name: "TheMoon".localized, emoji: "🌑", color: .gray),
        Location(name: "Camping".localized, emoji: "🏜️", color: .gray),
        Location(name: "HellFire".localized, emoji: "👹", color: .gray),
        Location(name: "Haven".localized, emoji: "😇", color: .gray),
        Location(name: "LuandryMat".localized, emoji: "👔", color: .gray),
        Location(name: "Farm".localized, emoji: "👨🏻‍🌾", color: .gray),
        Location(name: "CarDealerShip".localized, emoji: "🚘", color: .gray),
        Location(name: "BarbarShop".localized, emoji: "💈", color: .gray),
        Location(name: "SuperMarket".localized, emoji: "🏪", color: .gray),
        Location(name: "JACC".localized, emoji: "🏪", color: .gray),
        Location(name: "SouqAl-Mubarakiya".localized, emoji: "🛍️", color: .gray),
        Location(name: "GrandMosque".localized, emoji: "🕌", color: .gray),
        Location(name: "AlShaheedPark".localized, emoji: "🌳", color: .gray),
        Location(name: "SouqSharq".localized, emoji: "🛒", color: .gray),
        Location(name: "TheScientificCenter".localized, emoji: "🔬", color: .gray),
        Location(name: "KuwaitZoo".localized, emoji: "🦁", color: .gray),
        Location(name: "EntertainmentCity".localized, emoji: "🎢", color: .gray),
        Location(name: "SeifPalace".localized, emoji: "🏰", color: .gray),
        Location(name: "TheAvenues".localized, emoji: "🛒", color: .gray),
        Location(name: "SabahAlAhmadNatureReserve".localized, emoji: "🌿", color: .gray),
        Location(name: "FridayMarket".localized, emoji: "🎪", color: .gray),
        Location(name: "LiberationTower".localized, emoji: "📡", color: .gray),
        Location(name: "KuwaitEquestrianClub".localized, emoji: "🐎", color: .gray),
        Location(name: "KuwaitNationalLibrary".localized, emoji: "📚", color: .gray),
        Location(name: "FailakaIsland".localized, emoji: "⛵", color: .gray),
        Location(name: "AlRayaMall".localized, emoji: "🛍️", color: .gray),
        Location(name: "KhiranResort".localized, emoji: "🏖️", color: .gray),
        Location(name: "360Mall".localized, emoji: "🏢", color: .gray),
        Location(name: "QadsiaSportsClub".localized, emoji: "🏆", color: .gray),
        Location(name: "AlKoutMall".localized, emoji: "🏬", color: .gray),
        Location(name: "FishMarket".localized, emoji: "🐟", color: .gray),
        Location(name: "MuroojComplex".localized, emoji: "🍽️", color: .gray),
        Location(name: "IceSkatingRink".localized, emoji: "⛸️", color: .gray),
        Location(name: "KuwaitOperaHouse".localized, emoji: "🎶", color: .gray),
        Location(name: "KuwaitInternationalAirport".localized, emoji: "✈️", color: .gray),
        Location(name: "JaberInternationalStadium".localized, emoji: "🏟️", color: .gray),
        Location(name: "ShuwaikhIndustrialArea".localized, emoji: "🏭", color: .gray),
        Location(name: "KuwaitUniversity".localized, emoji: "🎓", color: .gray),
    ].shuffled()
}
